### ISSUE TITLE
FE: Refactored Login and Registration components with custom Form

### ISSUE THREAD

**Issue by Mleng89** [Type-Any-Whos/Any-Hoots#17]
## Changes addressing PR #2 

- Created a custom form component in `src/component/forms` with its own ContextProvider.
- Created utils folder (`src/utils/`) to abstract some of the Form behavior used in AuthPage.
    - Renamed `util.ts` to `fetchApi.ts` and moved it into newly created utils folder.
- Removed Login/Register Page as per #2 and replaced it with AuthPage.

---

## Summary of Additional Changes*

- Removed `import React from "react";` wherever possible due to [JSX Transforms](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) in React 17+ 
   - Added `.vscode/settings.json` as a precautionary measure to ensure VSCode does not raise false positives in your respective environments _(without this, VSCode may **incorrectly** display `'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.`; the application will successfully compile regardless)._
- Removed additional `//@ts-ignore`s (e.g., e745a0e) from backend and frontend files; since this was resolved in #13 and is a minor change, I decided to sneak in these deletions. :) 

##### *I will separate tasks into smaller PRs next time... O_O

---

#### TODO

- [x] Create Form component enclosed in ContextProviders

    - [x] Redesign FormConsumer for modern React component composition

- [x] Clean/refactor

### Log (last edit: 05/09/2021)

In effort to keep things DRY, I studied current composition of code and decided to start tackling this issue by creating a custom stateful form component with React's Context API to simplify prop drilling should the form component expand into multiple smaller components (e.g., `<Input />`).

I am currently considering using either `window.location.pathname` or state in `<Form />` to streamline logic in order to eliminate the need for an extra form.
    - I am sticking to using `window.location.pathname` to control flow in `<AuthPage />` for the time being.

- [x] As of commit b78981c, you will see an example of `window.location.pathname` being implemented to control which partial form to render; the partial form rendering can be replaced with a prop in order to reduce codebase.
- [x] As of commit 60e8ad1, figured out how to fix the various type errors in my custom Form component. I also added custom `displayName`s to make it easier to identify through React DevTools on Chrome.
- [x] Clean and refactor as my final step.
